name: Terceiro WorkFlow, falho , com dependências de jobs

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs: 
  job1:
    name: Tarefa 1
    runs-on: ubuntu-latest

    steps:
      - name: Passo 1
        run: echo "Passo 1"

      - name: Passo 2
        run: echo "Passo 2"

      - name: Passo ...
        run: echo "Passo ..."

  job2:
    name: Tarefa 2
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: Passo 1
        run: echo "Passo 1"

      - name: Passo 2
        run: echo "Passo 2"

      - name: Passo Falho
        run: echo "Passo Falho" | exit 1

  job3:
    name: Tarefa 3
    needs: job2
    runs-on: ubuntu-latest

    steps:
      - name: Passo 1
        run: echo "Passo 1"

      - name: Passo 2
        run: echo "Passo 2"

      - name: Passo ...
        run: echo "Passo ..."
